version: '3'
services:
  web:
    build: 
      context: web-server/
      dockerfile: Dockerfile
    ports:
      - "8123:8123"
  transaction:
    depends_on:
      - transaction-db
    build: 
      context: transaction-server/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  transaction-db:
    build: 
      context: transaction-server/postgres/
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    volumes:  
      - transaction-db:/data
  audit:
    depends_on:
      - audit-db
    build: 
      context: audit-server/
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
  audit-db:
    build: 
      context: audit-server/crate/
      dockerfile: Dockerfile
    ports:
      - "4201:4200"
      - "4301:4300"
    volumes:
      - audit-db:/data
  audit-mq:
    image: rabbitmq:latest
    ports:
      - "5673:5672"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
volumes:
  transaction-db:
  audit-db:
 


