version: '3'
services:
  nginx:
    build: 
      context: nginx/
      dockerfile: Dockerfile-local
    ports:
      - "8123:8123"
  transaction:
    environment:
      - DEBUG=TRUE
    depends_on:
      - transaction-db
      - audit-mq
    build: 
      context: transaction-server/
      dockerfile: Dockerfile-local
    ports:
      - "8080:8080"
    restart: on-failure
  transaction-db:
    build: 
      context: transaction-server/postgres/
      dockerfile: Dockerfile-local
    ports:
      - "5432:5432"
    volumes:  
      - transaction-db:/data
  audit:
    depends_on:
      - audit-db
      - audit-mq
    build: 
      context: audit-server/
      dockerfile: Dockerfile-local
    ports:
      - "8081:8081"
    restart: on-failure
  audit-db:
    build: 
      context: audit-server/crate/
      dockerfile: Dockerfile-local
    ports:
      - "4201:4200"
    volumes:
      - audit-db:/data
  audit-mq:
    image: "rabbitmq:alpine" 
    ports:
      - "5672:5672"       
      - "15672:15672"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
volumes:
  transaction-db:
  audit-db:
 


